# Page settings

baseURL = "https://venturadelmonte.github.io/"
languageCode = "en"
title = "Bonaventura Del Monte, Ph.D."
#theme = "hugo-devresume-theme"
#googleAnalytics = "UA-XXXXXXX-Y"



[params]
    author = "Bonaventura Del Monte"
    description = "Bonaventura Del Monte's personal website"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        title = "Ph.D."
        name = "Bonaventura"
        surname = "Del Monte"
        tagline = "Senior Software Engineer"
        avatar = "mypic.jpg"







    [params.contact]
        enable = true
        location = "Zürich, Switzerland"

        #[[params.contact.list]]
        #icon = "fas fa-phone-square"
        #url = "tel:#"
        #text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "venturadelmonte [at] gmail [dot] com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://venturadelmonte.github.io/"
        text = "https://venturadelmonte.github.io/"







    [params.skills]
        enable = false

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "C++"
        

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "PhD in Computer Science"
        university = "Technische Universität Berlin"
        dates = "2016 - 2022"
        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "University of Salerno"
        dates = "2013 - 2016"
        [[params.education.list]]
        degree = "BSc in Computer Science"
        university = "University of Salerno"
        dates = "2010 - 2013"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Software Campus"
        body = "Graduate of development program for future IT executives"
        date = "2020"
        link = "https://softwarecampus.de/certificates/17842/"
       








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Italian"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "German"
        level = "Intermediate"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = """Former Senior Researcher at
[Technical University Berlin](https://www.dima.tu-berlin.de/menue/database_systems_and_information_management_group/?no_cache=1)
collaborating with
[Volker Markl](https://www.dima.tu-berlin.de/menue/mitarbeiter/volker_markl),
[Tilmann Rabl](https://hpi.de/rabl/team/prof-dr-tilmann-rabl.html), and [Steffen Zeuch](http://www.user.tu-berlin.de/zeuchste/).

My research interests deal with designing and 
developing distributed data processing
engines using modern hardware
for scalable, reliable, and efficient stateful stream processing.
I published research papers at different venues including ACM SIGMOD, VLDB, and CIDR.
<!-- {: class="text-justify"} -->

I successfully defended my Ph.D. thesis about "Hardware-conscious techniques for efficient and reliable stateful stream processing" on December 5, 2022. Members of evaluation committee were [Volker Markl](https://www.dima.tu-berlin.de/menue/mitarbeiter/volker_markl),
[Tilmann Rabl](https://hpi.de/rabl/team/prof-dr-tilmann-rabl.html), [Peter Pietzuch](https://www.imperial.ac.uk/people/prp), [Matei Zaharia](https://cs.stanford.edu/people/matei/), and [Stefan Schmid](https://schmiste.github.io/).

Before joining TU Berlin and DFKI,
I received my MSc degree from
[University of Salerno](https://www.unisa.it)
in collaboration with the
[Distributed and Parallel Systems Group, Innsbruck](http://dps.uibk.ac.at/en/index.html)
under supervision of
[Radu Prodan](http://dps.uibk.ac.at/~radu/)
and
[Vittorio Scarano](http://docenti.unisa.it/001717/home).
I developed my Master's thesis while participating to an Erasmus+ program.
"""




    [params.publications]

        enable = true
        [[params.publications.list]]
            title = "Hardware-conscious techniques for efficient and reliable stateful stream processing"
            authors = "Bonaventura Del Monte"
            venue = "Ph.D. Thesis"
            link = "https://depositonce.tu-berlin.de/items/2cc894d9-aaa4-4401-9091-59002f83439a"
            slides = "assets/pdfs/PhD_Talk.pdf"
            fullvenue = "Technische Universität Berlin"
        [[params.publications.list]]
            title = "Rethinking Stateful Stream Processing with RDMA"
            authors = "Bonaventura Del Monte, Steffen Zeuch, Tilmann Rabl, Volker Markl."
            venue = "SIGMOD'22"
            link = "https://dl.acm.org/doi/abs/10.1145/3514221.3517826"
            slides = "assets/pdfs/SlashSigmod2022.pdf"
            fullvenue = "2022 ACM SIGMOD International Conference on Management of Data, Philadelphia, USA, 2022."
        [[params.publications.list]]
            title = "NebulaStream: Complex Analytics Beyond the Cloud"
            authors = "Steffen Zeuch, Eleni Tzirita Zacharatou, Shuhao Zhang, Xenofon Chatziliadis, Ankit Chaudhary, Bonaventura Del Monte, Dimitrios Giouroukis, Philipp M. Grulich, Ariane Ziehn, Volker Markl."
            venue = "VLDB'20"
            link = "https://www.nebula.stream/paper/zeuch_vliot.pdf"
            slides = ""
            fullvenue = "Very Large Databases Conference, Tokyo, Japan, 2020."
        [[params.publications.list]]
            title = "Rhino: Efficient Management of Very Large Distributed State for Stream Processing Engines"
            authors = "Bonaventura Del Monte, Steffen Zeuch, Tilmann Rabl, Volker Markl."
            venue = "SIGMOD'20"
            link = "https://dl.acm.org/doi/10.1145/3318464.3389723"
            slides = "https://www.slideshare.net/BonaventuraDelMonte/rhino-efficient-management-of-very-large-distributed-state-for-stream-processing-engines"
            fullvenue = "2020 ACM SIGMOD International Conference on Management of Data, Portland, USA, 2020."
        [[params.publications.list]]
            title = "The NebulaStream Platform: Data and Application Management for the Internet of Things"
            authors = "Steffen Zeuch, Ankit Chaudhary, Bonaventura Del Monte, Haralampos Gavriilidis, Dimitrios Giouroukis, Philipp M. Grulich, Sebastian Bress, Jonas Traub, Volker Markl."
            venue = "CIDR'20"
            link = "http://cidrdb.org/cidr2020/papers/p7-zeuch-cidr20.pdf"
            slides = ""
            fullvenue = "Biennial Conference on Innovative Data Systems, Amsterdam, Netherlands, 2020."
        [[params.publications.list]]
            title = "Analyzing efficient stream processing on modern hardware"
            authors = "Steffen Zeuch, Bonaventura Del Monte, Jeyhun Karimov, Clemens Lutz, Manuel Renz, Jonas Traub, Sebastian Breß, Tilmann Rabl, and Volker Markl"
            venue = "VLDB'19"
            link = "http://www.vldb.org/pvldb/vol12/p516-zeuch.pdf"
            slides = ""
            fullvenue = "International Conference on Very Large Data Bases (VLDB-2019), Los Angeles, USA, 2019"
        [[params.publications.list]]
            title = "On-the-fly Reconfiguration of Query Plans for Stateful Stream Processing Engines"
            authors = "Adrian Bartnik, Bonaventura Del Monte, Tilmann Rabl and Volker Markl"
            venue = "BTW'19"
            link = "http://www.redaktion.tu-berlin.de/fileadmin/fg131/Publikation/Papers/on-the-fly-reconfiguration_bartnik-2019.pdf"
            slides = ""
            fullvenue = "Tagungsband Datenbanksysteme für Business, Technologie und Web (BTW 2019), Rostock, Germany, 2019"
        [[params.publications.list]]
            title = "Efficient Migration of Very Large Distributed State for Scalable Stream Processing"
            authors = "Bonaventura Del Monte"
            venue = "VLDB'17"
            link = "http://ceur-ws.org/Vol-1882/paper01.pdf"
            slides = ""
            fullvenue = "Proceedings of the VLDB 2017 PhD Workshop. International Conference on Very Large Data Bases (VLDB-2017), located at co-located with the 43rd International Conference on Very Large Databases (VLDB 2017), August 28, München, Germany, 2017"
        [[params.publications.list]]
            title = "PROTEUS: Scalable Online Machine Learning for Predictive Analytics and Real-Time Interactive Visualization"
            authors = "Bonaventura Del Monte, Jeyhun Karimov, Alireza Rezaei Mahdiraji, Tilmann Rabl, Volker Markl"
            venue = "EDBT'17"
            link = "http://ceur-ws.org/Vol-1810/EuroPro_paper_03.pdf"
            slides = ""
            fullvenue = "International Workshop on Big Data Management in European Projects (EuroPro), 1st, located at Joint Conference EDBT/ICDT, March 21, Venice, Italy, 2017"
        [[params.publications.list]]
            title = "A scalable GPU-enabled framework for training deep neural networks"
            authors = "Bonaventura Del Monte, Radu Prodan"
            venue = "ICGHPC'16"
            link = "http://ieeexplore.ieee.org/abstract/document/7508071/"
            slides = ""
            fullvenue = "2nd IEEE Int. Conf. on Green High Performance Computing (ICGHPC'16), Nagercoil, India, February 26-27, 2016"

    [params.experience]
        enable = false

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "NebulaStream"
        meta = "Open Source"
        tagline = "I am actively involved as lead scientist in the development of [NebulaStream](https://www.nebula.stream/): a general purpose, end-to-end data management system for the IoT."

        [[params.projects.list]]
        title = "Rhino"
        meta = "Open Source"
        tagline = "I was a recipient of a [Software Campus](https://www.softwarecampus.de) award and the principal investigator of the [Rhino Project](https://www.dima.tu-berlin.de/menue/research/current_projects/rhino/) in collaboration with [Huawei Technologies LTD](https://www.huawei.com/)."

       








    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/VenturaDelMonte"
        title = "VenturaDelMonte"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/bonaventuradelmonte"
        title = "bonaventuradelmonte"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/VenturaDelMonte"
        title = "@VenturaDelMonte"





